
service: "ddl-handler"
frameworkVersion: "2"
provider:
  name: "aws"
  runtime: "nodejs12.x"
  stage: "dev"
  region: "us-east-1"
resources:
  Resources:
    restaurantSummary:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
        - AttributeName: "displayLanguage"
          AttributeType: "S"
        - AttributeName: "creationDate"
          AttributeType: "N"
        - AttributeName: "currentReviewStars"
          AttributeType: "S"
        - AttributeName: "restaurantNumber"
          AttributeType: "S"
        - AttributeName: "addressLat__long"
          AttributeType: "S"
        - AttributeName: "chefId"
          AttributeType: "S"
        - AttributeName: "isAvailableForChatNow"
          AttributeType: "S"
        KeySchema:
        - AttributeName: "displayLanguage"
          KeyType: "HASH"
        - AttributeName: "creationDate"
          KeyType: "RANGE"
        ProvisionedThroughput:
          ReadCapacityUnits: "5"
          WriteCapacityUnits: "5"
        TableName: "restaurantSummary"
        GlobalSecondaryIndexes:
        - IndexName: "GSI_currentReviewStars"
          KeySchema:
          - AttributeName: "currentReviewStars"
            KeyType: "HASH"
          Projection:
            NonKeyAttributes: []
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: "5"
            WriteCapacityUnits: "5"
        LocalSecondaryIndexes:
        - IndexName: "LSI_restaurantNumber"
          KeySchema:
          - AttributeName: "displayLanguage"
            KeyType: "HASH"
          - AttributeName: "restaurantNumber"
            KeyType: "RANGE"
          Projection:
            NonKeyAttributes: []
            ProjectionType: "ALL"
        - IndexName: "LSI_addressLat__long"
          KeySchema:
          - AttributeName: "displayLanguage"
            KeyType: "HASH"
          - AttributeName: "addressLat__long"
            KeyType: "RANGE"
          Projection:
            NonKeyAttributes: []
            ProjectionType: "ALL"
        - IndexName: "LSI_chefId"
          KeySchema:
          - AttributeName: "displayLanguage"
            KeyType: "HASH"
          - AttributeName: "chefId"
            KeyType: "RANGE"
          Projection:
            NonKeyAttributes: []
            ProjectionType: "ALL"
        - IndexName: "LSI_isAvailableForChatNow"
          KeySchema:
          - AttributeName: "displayLanguage"
            KeyType: "HASH"
          - AttributeName: "isAvailableForChatNow"
            KeyType: "RANGE"
          Projection:
            NonKeyAttributes: []
            ProjectionType: "ALL"
